using System.Collections.Generic;
using System.Linq;
using Dtos;
using Models;

namespace Services.Mappers
{
    public class OrderMapper : IOrderMapper
    {
        public OrderDto ToDto(Order o) =>
            new OrderDto
            {
                OrderId = o.OrderId,
                CustomerName = o.CustomerName ?? string.Empty,
                DatePlaced = o.DatePlaced,
                Items = (o.Items ?? Enumerable.Empty<InventoryItem>()).Select(ii => new InventoryItemDto
                {
                    ItemId = ii.ItemId,
                    Name = ii.Name ?? string.Empty,
                    Quantity = ii.Quantity,
                    Location = ii.Location ?? string.Empty
                }).ToList()
            };

        public List<OrderDto> ToDtoList(IEnumerable<Order> entities) =>
            entities.Select(ToDto).ToList();

        public Order CreateEntityForPersistence(Order incomingOrder, IEnumerable<InventoryItem> finalItems)
        {
            // We expect incomingOrder to already be validated by the controller.
            var order = new Order
            {
                // OrderId will be generated by EF when saving
                CustomerName = incomingOrder.CustomerName,
                DatePlaced = incomingOrder.DatePlaced == default ? System.DateTime.UtcNow : incomingOrder.DatePlaced,
                Items = finalItems.ToList()
            };

            return order;
        }
    }
}
